name: blue-green-deploy-using-job

on: [workflow_dispatch]

env:
    APP_NAME: gateway
    PACKAGE_PATH: piggymetrics

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file ${{ env.PACKAGE_PATH }}/pom.xml -DskipTests

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-files
        path: ./${{ env.PACKAGE_PATH }}/**/target/**.jar

  deploy-app:
    uses: Azure-Samples/azure-spring-cloud-blue-green/.github/workflows/blue-green-deploy-job.yml@main
    needs: build
    with: 
      AZURE_RESOURCEGROUP_NAME: spring-cloud-rg
      SPRING_CLOUD_SERVICE: spring-cloud-service
      APP_NAME: gateway
      ARTIFACT: jar-files
      JARPATH: gateway.jar
      ENVIRONMENT: Production
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

