name: simple-deploy

on: [workflow_dispatch]

env:
    AZURE_RESOURCEGROUP_NAME: spring-cloud-rg
    SPRING_CLOUD_SERVICE: spring-cloud-service
    APP_NAME: gateway
    PACKAGE_PATH: piggymetrics

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file ${{env.PACKAGE_PATH}}/pom.xml -DskipTests

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az extension add --yes --name spring-cloud
          az config set defaults.group=${{env.AZURE_RESOURCEGROUP_NAME}}
          az config set defaults.spring-cloud=${{env.SPRING_CLOUD_SERVICE}}
          az spring-cloud app list -o table
          az spring-cloud app deploy -n ${{env.APP_NAME}} --artifact-path $GITHUB_WORKSPACE/${{env.PACKAGE_PATH}}/${{env.APP_NAME}}/target/${{env.APP_NAME}}*.jar --verbose
